---
- name: configure ssh key
  hosts: all
  tasks:
    - name: upload key
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
